module.exports = {
  LOGIN: "/login",
  REFRESH: "/refresh",
  LOGOUT: "/logout",
  COMMENTS: "/comments",
  COMMENT_ID: "/comment/:id",
  CAMERAS: "/cameras",
  CAMERA_ID: "/camera/:id",
  NOTES: "/notes",
  NOTE_ID: "/note/:id",
  TRANSACTIONS: "/transactions",
  TRANSACTION_ID: "/transaction/:id",
  USERS: "/users",
  USER_ID: "/user/:id",
};
